#!/usr/bin/env python
import os
os.environ['ETS_TOOLKIT'] = 'qt4'
from PyQt4 import QtGui
import sys
import optparse

def main():
    usage = 'usage: %prog [options]'
    
    op = optparse.OptionParser(usage=usage)
    op.add_option('-m', '--main-file', dest='image',
                  help='To be plotted as a base image', type='string',
                  default=None)
    
    (opts, args) = op.parse_args()

    # THIS MUST HAPPEN FIRST BEFORE IMPORTING ENTHOUGHT STUFF!!!
    app = QtGui.QApplication(sys.argv)

    # register the nutmeg plugin before launching the ortho viewer
    from nutmeg import register_xipy_tools
    register_xipy_tools()

    from xipy.vis.three_dee_viewer import MayaviViewer

    win = MayaviViewer(image=opts.image)

    win.show()
    return win, app

if __name__=='__main__':
    win, app = main()
    sys.exit(app.exec_())
    
