#!/usr/bin/env python
import os
os.environ['ETS_TOOLKIT'] = 'qt4'
from PyQt4 import QtGui
import sys
import optparse

def main():

    usage = 'usage: %prog [options]'
    
    op = optparse.OptionParser(usage=usage)
    op.add_option('-m', '--main-file', dest='image',
                  help='To be plotted as a base image', type='string',
                  default=None)
    op.add_option('-b', '--beam-file', dest='beam',
                  help='Nutmeg beam file to use for overlays', type='string',
                  default=None)
    op.add_option('-2', '--2donly', dest='no_mayavi_viewer',
                  action='store_true',
                  help='Do not launch the 3D viewer',
                  default=False)

    
    (opts, args) = op.parse_args()

    # THIS MUST HAPPEN FIRST BEFORE IMPORTING ENTHOUGHT STUFF!!!
    app = QtGui.QApplication(sys.argv)
    from nutmeg import register_xipy_tools
    from nutmeg.core import tfbeam
    from nutmeg.vis import plot_tfbeam
    register_xipy_tools()

    if opts.beam:
        b = tfbeam.load_tfbeam(opts.beam)
        win = plot_tfbeam(b, with3d= not opts.no_mayavi_viewer)
    else:
        from xipy.vis.ortho_viewer import ortho_viewer
        win = ortho_viewer(image=opts.image,
                           mayavi_viewer=not opts.no_mayavi_viewer)

    win.show()
    return win, app

if __name__=='__main__':
    win, app = main()
    sys.exit(app.exec_())
